### ISSUE TITLE
Heavy Glitches on R9 390

### ISSUE THREAD

**Issue by julhe** [GPUOpen-Effects/FidelityFX-CACAO#1]
![grafik](https://user-images.githubusercontent.com/18037091/81814129-a7858f80-9528-11ea-8fee-c2cc12a02c46.png)

Im using the latest AMD driver 20.4.2 and builded from source. Same happends with the release build.

**Comment by jayfraser** [comment]
Hi, thanks for reporting this! I'll investigate the issue as soon as possible.

**Comment by rekongstor** [comment]
Same problem on R7 370.
Although, it is still possible to run this sample on the CPU at the cost of performance. At least glitches are gone.
