### ISSUE TITLE
No data to support your claims?

### ISSUE THREAD

**Issue by NostraDavid** [GPUOpen-Effects/FidelityFX-CACAO#2]
This claim is made:

> (CACAO) is a highly optimized adaptive sampling ambient occlusion implementation.

But there's no data available **how much** better it does vs Intel's ASSAO or Nvidia's HBAO+ or VXAO.

Will such data be made available on a later date?

**Comment by SurenaSKQ** [comment]
HBAO, ASSAO, and CACAO are essentially very close technologies. VXAO (and other voxel-based AO) is superior to all of them, and CACAO, HBAO and ASSAO are all the same level of quality.

**Comment by NostraDavid** [comment]
Ahh, that makes sense! Thanks for letting me know!
