### ISSUE TITLE
Reduction in Quality between V1.0 and V1.1

### ISSUE THREAD

**Issue by clayjohn** [GPUOpen-Effects/FidelityFX-CACAO#7]
First of all, thank you for your hard work and for making this open-source! It is genuinely appreciated by those of us looking to learn from examples, and looking to benefit off your hard work in our engines. :) 

### Background
I am a contributor to [Godot](www.godotengine.org) which is an open-source game engine. We have been evaluating new methods for SSAO for a few months now. We were planning on using ASSAO when we found out about CACAO. However, once trying CACAO v1.1 we noticed the quality did not match the promotional images at all. However, we noticed CACAO v1.0 looks great!

### The Issues

- V1.1 substantially reduces the quality of CACAO compared to v1.0.

- ~V1.1 restricts itself to only using the downsampled version~ _edit I now see the note in ffx_cacao.h https://github.com/GPUOpen-Effects/FidelityFX-CACAO/blob/ac4b575380a9346f931028ebae1fb4db4a031da9/ffx-cacao/inc/ffx_cacao.h#L25-L29_

- V1.1 is blurred much more heavily than the downsampled version in V1.0

- In V1.1 "adaptive quality" doesn't actually impact the image quality, even when set to "highest quality"

I have included screenshots below to illustrate the issue.

Could these issues be addressed in a subsequent point release or a bug fixing commit? I ask because I am unfamiliar with your development approach/priorities. For us working on Godot, we would love to see these issues addressed and then we could port CACAO directly into Godot. But if not, we totally understand. Thanks anyway!

**Version 1.0:**
![Screenshot (10)](https://user-images.githubusercontent.com/16521339/97788514-b4e61300-1b76-11eb-8a2a-54a0d15d8dc9.png)
![Screenshot (16)](https://user-images.githubusercontent.com/16521339/97788547-ea8afc00-1b76-11eb-8460-93078e664e93.png)

**Version 1.1:**
![Screenshot (11)](https://user-images.githubusercontent.com/16521339/97788515-b7486d00-1b76-11eb-8d71-f3a0c32a0f42.png)
![Screenshot (15)](https://user-images.githubusercontent.com/16521339/97788545-e959cf00-1b76-11eb-9241-aa38edd25435.png)

**Version 1.0 downsampled**
![Screenshot (17)](https://user-images.githubusercontent.com/16521339/97788706-0773ff00-1b78-11eb-9e67-c28711e4e4a8.png)
![Screenshot (18)](https://user-images.githubusercontent.com/16521339/97788707-093dc280-1b78-11eb-8423-fb2325ea89a7.png)

**Comment by reduz** [comment]
![image](https://user-images.githubusercontent.com/6265307/97789757-bda00e80-1ba1-11eb-8eca-498e79f40081.png)
I also want to note that Intel's ASSAO looks considerably sharper when upscaled (and sharper than CACAO full res). I am not sure if this is a problem with CACAO's implementation.

**Comment by clayjohn** [comment]
With the release of v1.2 and the restoration of native size it looks like these issues are gone. 

Thanks for your hard work! CACAO has been a great learning resource for me.
